### ISSUE TITLE
Time Based Animations

### ISSUE THREAD

**Issue by chiefpumba** [overlay-expert/help-desk#130]
**Is your feature request related to a problem? Please describe.**
Timed based animation/alerts. 

**Describe the solution you'd like**
I am trying to create an Alert on a timed based animation loop. I am trying to create social media pop ups that loop throughout my stream but don't understand how to properly set up the time based animation to make this work. For example if I want to set up 3 social media pop up animations to rotate between each other I am not sure how to get it to work.

**Screenshots**
![image](https://user-images.githubusercontent.com/75697173/101533319-ac49df00-3963-11eb-8251-8cd3a510042b.png)

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

**Comment by marcandrews** [comment]
To do this using time-based layers will be challenging because you will have to delay the second layer by `12000 ms` (includes the `1000 ms` entry animation and `1000 ms `exit animation) and the third layer by `24000 ms` ... I think :sweat_smile:

This is much easier to accomplish by adding **multiple text groups to the same layer**. Don't worry, you can include images in a text group too. See the Green Damask overlay template for an example.

![Screenshot from 2020-12-08 17-38-32](https://user-images.githubusercontent.com/3518829/101549977-9694e380-397c-11eb-9747-e14feff6a3d4.png)

Let me know how it works out.
