### ISSUE TITLE
cannot save my overlay

### ISSUE THREAD

**Issue by goobieduke69** [overlay-expert/help-desk#232]
**Describe the bug**
It says "Aw, snap!
Something went wrong while trying to complete your request. If the problem persists, please contact support."
**To Reproduce**
1. Go to 'my layers'
2. Click on 'save'
3. See error

**Expected behavior**
I expected to be able to save it.

**Twitch channel**
https://twitch.tv/goobieduke69

**Screenshots**
[e.g. Builder, Extension Configuration Screen, etc.]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I just would like to be able for this to work and play on my stream

**Comment by marcandrews** [comment]
There is currently a bug where it does not show you which layers are invalid when saving fails. Until this bug is resolved, you will need to go through your layers one-by-one, look for the red "Please resolve errors before continuing" alert near the top and resolve each error in each layer before trying to save again.
