### ISSUE TITLE
Error when I try to "Choose" any Overlay

### ISSUE THREAD

**Issue by MoodiPanda** [overlay-expert/help-desk#258]
I'm getting an error , I tried to "Choose" my Overlay on Google Chrome, Internet explorer, Firefox and IOS Browser and im getting "An error was encountered. Please try again. If the problem persists, please contact us." I even tried to "Choose" a Blank overlay and Im still getting an error Twitch: MoodiPanda

**Describe the bug**
cannot select the "choose" button without getting "An error was encountered. Please try again. If the problem persists, please contact us.
Web
[overlay.expert/support](https://overlay.expert/support)"

**Expected behavior**
I followed a youtube tutorial step by step

**Twitch channel**
https://twitch.tv/MoodiPanda

Windows 10 and windows 7
Firefox, Google chrome, Microsoft Edge

Iphone xr
Safari Browser

**Comment by Umju-Twitch** [comment]
I'm having this same issue as well... Twitch - Umju

It lets me edit the overlay no issue, but once I try to "Choose" it gives me that same error message, not just with my created one,  but with all of them.

**Comment by Wizapp-zz** [comment]
Same for me, been trying most of the day to get this working.

Anyone any ideas?

**Comment by daddymac2004** [comment]
this has been a problem for me since yesterday after i made my first one it seems to be a bug for everyone and hopefully will be fixed soon but it does seem this hasnt been the first time it has happened but hopefully itll fix sooner better then later i wanna make my twitch look more professional since ive just hit affiliate not long ago. if itll help at all when a mod reads this chat my twitch is daddymac2004

**Comment by smileyfacekillz** [comment]
I'm having the same issue I'm still waiting for an answer

**Comment by marcandrews** [comment]
Duplicates #257

**Comment by elitehumanity** [comment]
Same issue here GT: SammyPresser199
