### ISSUE TITLE
Most Recent Sub Not Showing

### ISSUE THREAD

**Issue by artsyweebie** [overlay-expert/help-desk#290]
### Describe the bug

When people sub to me my “recent subscriber” tracker doesn’t change and stays on an old subscribers name. 
### To Reproduce

1. go to layer 2. click on content 3. edit the text 4. add “recent subscriber” option 5. see sub not update. 
### Expected behavior

I expect it to update the most recent subscriber just like it updates my most recent follower. 
### Twitch channel

twitch.tv/artsyweebie
### Device (PC, mobile, etc.):

- Device: 
iphone 11 
- OS: 
windows 11
- Browser: 
edge

**Comment by marcandrews** [comment]
Twitch made some updates and changed the way we get your subscribers and there may be a bug with the way Twitch is providing the information. Do you know who your last few subscribers were and when they subscribed?

**Comment by artsyweebie** [comment]
yes i believe so! and they subscribed last night!

**Comment by artsyweebie** [comment]
do you want the name of the subscribers?

**Comment by marcandrews** [comment]
> do you want the name of the subscribers?

Yes

**Comment by artsyweebie** [comment]
(most to least recent although these were the people who gifted) moxie_ampersand deptical jenieni 
i don’t know who they gifted to

**Comment by marcandrews** [comment]
According to the Twitch API, your most recent subs were kaptm_krunch, AIizanna and crashdowncoco and all of these were not gifted. Please check your overlay in the Builder and during a live stream (in the Extension) and confirm that this is what you see.

If these three subs are in fact not your latest subs, there is nothing we can do at the moment because this is the information we get from Twitch and the issue might be on their end.

**Comment by artsyweebie** [comment]
yeah those aren’t the three latest.
