### ISSUE TITLE
Twitter Handle unchanged in stream overlay after Twitter handle changed on Twitter.com

### ISSUE THREAD

**Issue by cptaha** [overlay-expert/help-desk#80]
Twitter account not changing to new handle in overlay, and i cant un-link and re-link my twitter. I have also tried remaking the layer and content layers respectively to no use.

1. Go to Overlay.expert
2. Create new overlay
3. add layer
4. add content to layer (twitter handle)(must link twitter acct. in this step)
5. save overlay on overlay.expert
6. go to twitch.tv
7. Link Overlay.expert to Twitch acct. in the extension tab of the creator tool menu.
8. go to twitter.com
9. Change twitter acct handle in settings and save.
10. Return to Overlay.expert and open saved overlay or go to twitch.tv channel linked to created overlay

**Expected behavior**
Twitter handle will not change in the overlay created on Overlay.expert 

**Twitch channel**
https://twitch.tv/Cptahab4

HP Envy 15 Notebook PC
Windows 10 Home x64
version 10.0.18362 Build 18362
O.S: Google Chrome
Version 85.0.4183.83 (Official Build) (64-bit)

**Comment by marcandrews** [comment]
Since you signed in with Twitter first, your Twitter account is your primary account on Overlay Expert and you cannot unlink your primary account.

To update your handle:
a) sign out of Overlay Expert and sign back in with Twitter 
~ or ~
b) in your My Account dialog, set your Twitch account to your primary account, and then re-link your Twitter account.

Let me know if this resolves your issue.

**Comment by cptaha** [comment]
The first solution worked like a charm. Thank you!!

**Comment by marcandrews** [comment]
Awesome 🎉
